# Mokapi-compatible mock file (simple OpenAPI-like)
openapi: 3.0.0
info:
  title: PayFlow Mock Payments
  version: "1.0"
paths:
  /initiatePayment:
    post:
      summary: Initiate payment
      requestBody:
        required: true
      responses:
        '200':
          description: payment accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                  status:
                    type: string
                  nextAction:
                    type: string
                example:
                  transactionId: tx_12345
                  status: pending
                  nextAction: otp_required
  /verifyPayment:
    post:
      summary: Verify payment (OTP)
      responses:
        '200':
          description: verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId: { type: string }
                  status: { type: string }
                  reason: { type: string }
              example:
                transactionId: tx_12345
                status: success
                reason: Verified
